### ISSUE TITLE
[BUG] Unable to access web UI

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-daapd#84] opened 2023-09-17 23:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm unable to access the web UI for Owntone at http://owntone.local:3689/ or http://ip:3689/ despite the container running. As the container starts, there are numerous fatal errors for mDNS failing to initialize, but eventually the container appears to start normally. I'm not sure if it matters, but I'm also running networks for Caddy and Gluetun on the same server. Stopping both containers does not resolve the issue or change the log.

Note that I had to trim the log down to fit within the character limit. The initialization message listing all the services and mDNS failing to init was listed dozens of times. 

### Expected Behavior

Owntone should be accessable at http://owntone.local:3689/ or http://ip:3689/.

### Steps To Reproduce

1. Initialize container using provided compose
2. Attempt to access web UI at http://owntone.local:3689/

### Environment

```markdown
- OS: Rocky Linux 9.2
- daapd version: 28.8
- How docker service was installed: Distro repositories/package manager
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3.9"

services:
  daapd:
    image: linuxserver/daapd:latest
    container_name: daapd
    restart: unless-stopped
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./music:/music
```
```


### Container logs

```bash
daapd  | [migrations] started
daapd  | [migrations] no migrations found
daapd  | ───────────────────────────────────────
daapd  | 
daapd  |       ██╗     ███████╗██╗ ██████╗ 
daapd  |       ██║     ██╔════╝██║██╔═══██╗
daapd  |       ██║     ███████╗██║██║   ██║
daapd  |       ██║     ╚════██║██║██║   ██║
daapd  |       ███████╗███████║██║╚██████╔╝
daapd  |       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
daapd  | 
daapd  |    Brought to you by linuxserver.io
daapd  | ───────────────────────────────────────
daapd  | 
daapd  | To support LSIO projects visit:
daapd  | https://www.linuxserver.io/donate/
daapd  | 
daapd  | ───────────────────────────────────────
daapd  | GID/UID
daapd  | ───────────────────────────────────────
daapd  | 
daapd  | User UID:    1000
daapd  | User GID:    1000
daapd  | ───────────────────────────────────────
daapd  | 
daapd  | [custom-init] No custom files found, skipping...
daapd  | [2023-09-17T15:11:36Z INFO  librespot] librespot 0.4.2 UNKNOWN (Built on 2023-08-01, Build ID: 1690865570, Profile: release)
daapd  | [2023-09-17T15:11:36Z WARN  libmdns] Failed to register IPv6 receiver: Os { code: 19, kind: Uncategorized, message: "No such device" }
daapd  | [ls.io-init] done.
daapd  | Failed to set ownership on logfile: Operation not permitted
daapd  | [2023-09-17 15:12:13] [  LOG]     main: OwnTone version 28.8 taking off
daapd  | [2023-09-17 15:12:13] [  LOG]     main: Built with:
daapd  | [2023-09-17 15:12:13] [  LOG]     main: - ffmpeg
daapd  | [2023-09-17 15:12:13] [  LOG]     main: - Spotify
daapd  | [2023-09-17 15:12:13] [  LOG]     main: - librespot-c
daapd  | [2023-09-17 15:12:13] [  LOG]     main: - LastFM
daapd  | [2023-09-17 15:12:13] [  LOG]     main: - Chromecast
daapd  | [2023-09-17 15:12:13] [  LOG]     main: - MPD
daapd  | [2023-09-17 15:12:13] [  LOG]     main: - Websockets
daapd  | [2023-09-17 15:12:13] [  LOG]     main: - ALSA
daapd  | [2023-09-17 15:12:13] [  LOG]     main: - Webinterface
daapd  | [2023-09-17 15:12:13] [  LOG]     main: - Regex
daapd  | [2023-09-17 15:12:13] [  LOG]     main: mDNS init
daapd  | [2023-09-17 15:12:13] [FATAL]     main: mDNS init failed
daapd  | [2023-09-17 15:12:13] [  LOG]     main: Exiting.
daapd  | Failed to set ownership on logfile: Operation not permitted
daapd  | [2023-09-17 15:12:46] [  LOG]     main: OwnTone version 28.8 taking off
daapd  | [2023-09-17 15:12:46] [  LOG]     main: Built with:
daapd  | [2023-09-17 15:12:46] [  LOG]     main: - ffmpeg
daapd  | [2023-09-17 15:12:46] [  LOG]     main: - Spotify
daapd  | [2023-09-17 15:12:46] [  LOG]     main: - librespot-c
daapd  | [2023-09-17 15:12:46] [  LOG]     main: - LastFM
daapd  | [2023-09-17 15:12:46] [  LOG]     main: - Chromecast
daapd  | [2023-09-17 15:12:46] [  LOG]     main: - MPD
daapd  | [2023-09-17 15:12:46] [  LOG]     main: - Websockets
daapd  | [2023-09-17 15:12:46] [  LOG]     main: - ALSA
daapd  | [2023-09-17 15:12:46] [  LOG]     main: - Webinterface
daapd  | [2023-09-17 15:12:46] [  LOG]     main: - Regex
daapd  | [2023-09-17 15:12:46] [  LOG]     main: mDNS init
daapd  | [2023-09-17 15:12:46] [FATAL]     main: mDNS init failed
daapd  | [2023-09-17 15:12:46] [  LOG]     main: Exiting.
daapd  | Failed to set ownership on logfile: Operation not permitted
daapd  | [2023-09-17 15:12:47] [  LOG]     main: OwnTone version 28.8 taking off
daapd  | [2023-09-17 15:12:47] [  LOG]     main: Built with:
daapd  | [2023-09-17 15:12:47] [  LOG]     main: - ffmpeg
daapd  | [2023-09-17 15:12:47] [  LOG]     main: - Spotify
daapd  | [2023-09-17 15:12:47] [  LOG]     main: - librespot-c
daapd  | [2023-09-17 15:12:47] [  LOG]     main: - LastFM
daapd  | [2023-09-17 15:12:47] [  LOG]     main: - Chromecast
daapd  | [2023-09-17 15:12:47] [  LOG]     main: - MPD
daapd  | [2023-09-17 15:12:47] [  LOG]     main: - Websockets
daapd  | [2023-09-17 15:12:47] [  LOG]     main: - ALSA
daapd  | [2023-09-17 15:12:47] [  LOG]     main: - Webinterface
daapd  | [2023-09-17 15:12:47] [  LOG]     main: - Regex
daapd  | [2023-09-17 15:12:47] [  LOG]     main: mDNS init
daapd  | [2023-09-17 15:12:47] [FATAL]     main: mDNS init failed
daapd  | [2023-09-17 15:12:47] [  LOG]     main: Exiting.
daapd  | Failed to set ownership on logfile: Operation not permitted
daapd  | [2023-09-17 15:12:48] [  LOG]     main: OwnTone version 28.8 taking off
daapd  | [2023-09-17 15:12:48] [  LOG]     main: Built with:
daapd  | [2023-09-17 15:12:48] [  LOG]     main: - ffmpeg
daapd  | [2023-09-17 15:12:48] [  LOG]     main: - Spotify
daapd  | [2023-09-17 15:12:48] [  LOG]     main: - librespot-c
daapd  | [2023-09-17 15:12:48] [  LOG]     main: - LastFM
daapd  | [2023-09-17 15:12:48] [  LOG]     main: - Chromecast
daapd  | [2023-09-17 15:12:48] [  LOG]     main: - MPD
daapd  | [2023-09-17 15:12:48] [  LOG]     main: - Websockets
daapd  | [2023-09-17 15:12:48] [  LOG]     main: - ALSA
daapd  | [2023-09-17 15:12:48] [  LOG]     main: - Webinterface
daapd  | [2023-09-17 15:12:48] [  LOG]     main: - Regex
daapd  | [2023-09-17 15:12:48] [  LOG]     main: mDNS init
daapd  | [2023-09-17 15:12:48] [FATAL]     main: mDNS init failed
daapd  | [2023-09-17 15:12:48] [  LOG]     main: Exiting.
daapd  | Failed to set ownership on logfile: Operation not permitted
daapd  | [2023-09-17 15:12:49] [  LOG]     main: OwnTone version 28.8 taking off
daapd  | [2023-09-17 15:12:49] [  LOG]     main: Built with:
daapd  | [2023-09-17 15:12:49] [  LOG]     main: - ffmpeg
daapd  | [2023-09-17 15:12:49] [  LOG]     main: - Spotify
daapd  | [2023-09-17 15:12:49] [  LOG]     main: - librespot-c
daapd  | [2023-09-17 15:12:49] [  LOG]     main: - LastFM
daapd  | [2023-09-17 15:12:49] [  LOG]     main: - Chromecast
daapd  | [2023-09-17 15:12:49] [  LOG]     main: - MPD
daapd  | [2023-09-17 15:12:49] [  LOG]     main: - Websockets
daapd  | [2023-09-17 15:12:49] [  LOG]     main: - ALSA
daapd  | [2023-09-17 15:12:49] [  LOG]     main: - Webinterface
daapd  | [2023-09-17 15:12:49] [  LOG]     main: - Regex
daapd  | [2023-09-17 15:12:49] [  LOG]     main: mDNS init
daapd  | [2023-09-17 15:12:49] [FATAL]     main: mDNS init failed
daapd  | [2023-09-17 15:12:49] [  LOG]     main: Exiting.
daapd  | Failed to set ownership on logfile: Operation not permitted
daapd  | [2023-09-17 15:12:50] [  LOG]     main: OwnTone version 28.8 taking off
daapd  | [2023-09-17 15:12:50] [  LOG]     main: Built with:
daapd  | [2023-09-17 15:12:50] [  LOG]     main: - ffmpeg
daapd  | [2023-09-17 15:12:50] [  LOG]     main: - Spotify
daapd  | [2023-09-17 15:12:50] [  LOG]     main: - librespot-c
daapd  | [2023-09-17 15:12:50] [  LOG]     main: - LastFM
daapd  | [2023-09-17 15:12:50] [  LOG]     main: - Chromecast
daapd  | [2023-09-17 15:12:50] [  LOG]     main: - MPD
daapd  | [2023-09-17 15:12:50] [  LOG]     main: - Websockets
daapd  | [2023-09-17 15:12:50] [  LOG]     main: - ALSA
daapd  | [2023-09-17 15:12:50] [  LOG]     main: - Webinterface
daapd  | [2023-09-17 15:12:50] [  LOG]     main: - Regex
daapd  | [2023-09-17 15:12:50] [  LOG]     main: mDNS init
daapd  | [2023-09-17 15:12:50] [FATAL]     main: mDNS init failed
daapd  | [2023-09-17 15:12:50] [  LOG]     main: Exiting.
daapd  | Failed to set ownership on logfile: Operation not permitted
daapd  | [2023-09-17 15:12:51] [  LOG]     main: OwnTone version 28.8 taking off
daapd  | [2023-09-17 15:12:51] [  LOG]     main: Built with:
daapd  | [2023-09-17 15:12:51] [  LOG]     main: - ffmpeg
daapd  | [2023-09-17 15:12:51] [  LOG]     main: - Spotify
daapd  | [2023-09-17 15:12:51] [  LOG]     main: - librespot-c
daapd  | [2023-09-17 15:12:51] [  LOG]     main: - LastFM
daapd  | [2023-09-17 15:12:51] [  LOG]     main: - Chromecast
daapd  | [2023-09-17 15:12:51] [  LOG]     main: - MPD
daapd  | [2023-09-17 15:12:51] [  LOG]     main: - Websockets
daapd  | [2023-09-17 15:12:51] [  LOG]     main: - ALSA
daapd  | [2023-09-17 15:12:51] [  LOG]     main: - Webinterface
daapd  | [2023-09-17 15:12:51] [  LOG]     main: - Regex
daapd  | [2023-09-17 15:12:51] [  LOG]     main: mDNS init
daapd  | [2023-09-17 15:12:51] [FATAL]     main: mDNS init failed
daapd  | [2023-09-17 15:12:51] [  LOG]     main: Exiting.
daapd  | Failed to set ownership on logfile: Operation not permitted
daapd  | [2023-09-17 15:12:52] [  LOG]     main: OwnTone version 28.8 taking off
daapd  | [2023-09-17 15:12:52] [  LOG]     main: Built with:
daapd  | [2023-09-17 15:12:52] [  LOG]     main: - ffmpeg
daapd  | [2023-09-17 15:12:52] [  LOG]     main: - Spotify
daapd  | [2023-09-17 15:12:52] [  LOG]     main: - librespot-c
daapd  | [2023-09-17 15:12:52] [  LOG]     main: - LastFM
daapd  | [2023-09-17 15:12:52] [  LOG]     main: - Chromecast
daapd  | [2023-09-17 15:12:52] [  LOG]     main: - MPD
daapd  | [2023-09-17 15:12:52] [  LOG]     main: - Websockets
daapd  | [2023-09-17 15:12:52] [  LOG]     main: - ALSA
daapd  | [2023-09-17 15:12:52] [  LOG]     main: - Webinterface
daapd  | [2023-09-17 15:12:52] [  LOG]     main: - Regex
daapd  | [2023-09-17 15:12:52] [  LOG]     main: mDNS init
daapd  | [2023-09-17 15:12:52] [FATAL]     main: mDNS init failed
daapd  | [2023-09-17 15:12:52] [  LOG]     main: Exiting.
daapd  | Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
daapd  | Successfully dropped root privileges.
daapd  | avahi-daemon 0.8 starting up.
daapd  | WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
daapd  | Loading service file /etc/avahi/services/sftp-ssh.service.
daapd  | Loading service file /etc/avahi/services/ssh.service.
daapd  | *** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
daapd  | Joining mDNS multicast group on interface eth0.IPv4 with address 172.17.0.2.
daapd  | New relevant interface eth0.IPv4 for mDNS.
daapd  | Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
daapd  | New relevant interface lo.IPv4 for mDNS.
daapd  | Network interface enumeration completed.
daapd  | Registering new address record for 172.17.0.2 on eth0.IPv4.
daapd  | Registering new address record for 127.0.0.1 on lo.IPv4.
daapd  | Failed to set ownership on logfile: Operation not permitted
daapd  | [2023-09-17 15:12:53] [  LOG]     main: OwnTone version 28.8 taking off
daapd  | [2023-09-17 15:12:53] [  LOG]     main: Built with:
daapd  | [2023-09-17 15:12:53] [  LOG]     main: - ffmpeg
daapd  | [2023-09-17 15:12:53] [  LOG]     main: - Spotify
daapd  | [2023-09-17 15:12:53] [  LOG]     main: - librespot-c
daapd  | [2023-09-17 15:12:53] [  LOG]     main: - LastFM
daapd  | [2023-09-17 15:12:53] [  LOG]     main: - Chromecast
daapd  | [2023-09-17 15:12:53] [  LOG]     main: - MPD
daapd  | [2023-09-17 15:12:53] [  LOG]     main: - Websockets
daapd  | [2023-09-17 15:12:53] [  LOG]     main: - ALSA
daapd  | [2023-09-17 15:12:53] [  LOG]     main: - Webinterface
daapd  | [2023-09-17 15:12:53] [  LOG]     main: - Regex
daapd  | [2023-09-17 15:12:53] [  LOG]     main: mDNS init
daapd  | [2023-09-17 15:12:53] [  LOG]     mdns: Avahi state change: Client registering
daapd  | [2023-09-17 15:12:53] [  LOG]       db: Configured to use database file '/config/dbase_and_logs/songs3.db'
daapd  | [2023-09-17 15:12:53] [  LOG]       db: Now vacuuming database, this may take some time...
daapd  | [2023-09-17 15:12:53] [  LOG]       db: Database OK with 0 active files and 6 active playlists
daapd  | ALSA lib confmisc.c:165:(snd_config_get_card) Cannot get card index for 0
daapd  | [2023-09-17 15:12:53] [  LOG]     scan: Bulk library scan completed in 0 sec
daapd  | [2023-09-17 15:12:53] [  LOG]  spotify: No spotify refresh token found
daapd  | [2023-09-17 15:12:53] [  LOG]  spotify: Spotify webapi token refresh failed. In order to use Spotify, authorize the server to access your saved tracks by visiting http://owntone.local:3689
daapd  | [2023-09-17 15:12:53] [  LOG]      lib: Library init scan completed in 0 sec (0 changes)
daapd  | Server startup complete. Host name is a0c8b1af22a5.local. Local service cookie is 678618950.
daapd  | [2023-09-17 15:12:54] [  LOG]     mdns: Avahi state change: Client running
daapd  | Service "a0c8b1af22a5" (/etc/avahi/services/ssh.service) successfully established.
daapd  | Service "a0c8b1af22a5" (/etc/avahi/services/sftp-ssh.service) successfully established.
```
```

**Comment by aptalca** [comment] 2023-09-18 02:11
You did not map any ports. Either map the ports, or run with host networking.

Closing, not a bug.

**Closed as completed by aptalca** 2023-09-18 02:11 UTC

**Comment by ghost** [comment] 2023-09-18 10:46
When I initially sought out support via Discord, I was told that port mapping didn't matter because the container ran in host mode (the logs will even warn that mapped ports will be ignored). Additionally, I was advised to set it to bridge mode in an attempt to access the web UI. If I set it back to host, I get an identical log. 

Could this issue please be reopened?

**Comment by aptalca** [comment] 2023-09-18 14:04
Please continue seeking support on discord. GitHub is for bug reports.
